### ISSUE TITLE
self signed certificate error when connecting to a remote RVI node

### ISSUE THREAD

**Issue by klooer** [GENIVI/rvi_lib#13]
I'm using the interactive example to connect to a remote RVI node which uses self signed certificates, but I always get the "err 18:self signed certificate ... ssl3_get_server_certificate" error no matter how I configure the system running the RVI lib to trust the certificate. Am I missing something? Thanks.

**Comment by tjamison** [comment]
Hi klooer, two questions: are you using the public test RVI node at 38.129.64.41:9010, or one that you have configured yourself? And are you using the supplied certificates or certificates that you have generated yourself?

Either way, the location of the public certificate of the Certification Authority (or authorities) must be specified in the configuration file in the section `"ca": { "cert": "...", "dir": "..." }`.

**Comment by klooer** [comment]
Hi tjamison,

Thanks for your response.

I have solved this issue by modifying the certificate/key configuration of the remote RVI node I've been running, to make the "device cert/key" of the remote rvi_core node to be same as the root CA cert/key - all of the certs/keys are generated by myself using openssl. The root cert has been added to the trust list of the device running the rvi_lib.

Not sure if this is the right approach but it just works for me. Hope to hear from you about your opinions.

Thanks.

**Comment by tjamison** [comment]
OK, just to make sure I understand, you have:

1. One public/private key pair with corresponding self-signed certificate for the root CA
2. Another public/private key pair with a certificate signed by the root CA

And you're using (1) as the device certificate for the node running rvi_core and (2) as the device certificate for the node running rvi_lib, correct?

This is an OK approach and very similar to what I run for development. In general though I'd recommend adding another public/private key pair, and a corresponding certificate signed by the root CA, and using _that_ one as the device certificate for the node running rvi_core. That way, if the certificate for the node running rvi_core is compromised, the root CA is not directly compromised (... thereby compromising all of the certificates signed by the root CA).

In general, RVI *doesn't* require that the same Root CA signs off on all certificates, only that the Root CAs are _mutually trusted_ by all nodes in a network (so any particular device may have multiple trusted certificates). This is typical for PKI and commercial CAs generally have certificates bundled with operating systems, browsers, etc, so that the installation/trust process is invisible to the end user.

**Comment by klooer** [comment]
Hi tjamison,

Thanks for the detailed explanations. Yes I think your understanding is correct - that's how I make the rvi_lib and rvi_core work together in my environment now.

Also thanks for the suggestions which I will surely take into consideration in the future.

Closing this issue.
